#!/usr/bin/env bash
# script that transfers a file from our client to a server
if ! [[ $4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

filetocp=$1
ip_dest=$2
user_name=$3
key=$4
scp -i "$key" -o StrictHostKeyChecking=no "$filetocp" "$user_name"@"$ip_dest":~/
