#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo chmod 777 /etc/nginx/sites-available/
str="location /redirect_me {\n     rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent; \n}"
sudo sed -i "/# pass the PHP/i $str" /etc/nginx/sites-enabled/default
sudo service nginx restart
