#!/usr/bin/env bash
#Nginx must be running, and listening on port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
