#!/usr/bin/env bash
#Bash script that creating
#Bash script that displays
echo $$ > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    trap "{ echo 'I hate the kill command' ; rm '/var/run/holbertonscript.pid' ; exit ; }" SIGTERM
    trap "{ echo 'Y U no love me?!' ; }" SIGINT
    trap "{ rm '/var/run/holbertonscript.pid' ; exit ; }" SIGQUIT
    sleep 2
done
