#!/usr/bin/env bash
#Bash script that creating
#Bash script that displays
echo $$ > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command' && rm '/var/run/holbertonscript.pid'" SIGTERM
trap "echo 'Y U no love me?!'"
while true
do
	echo "To infinity and beyond"
done
