#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9 print hi
i=1
while (( i <= 10 ))

do
    echo "Holberton School"

    if [ "$i" == "9" ]
    then
        echo "Hi"
    fi
    i=$(( i+1 ))
done
