#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9 print hi
i=1
while (( i <= 9 ))

do
    echo "Holberton School"
    i=$(( i+1 ))

    if [ "$i" == "9" ]
    then
        echo "Hi"
    fi
done
